"""Post-publication Team State generation hook (Share Cards SC-03B-02).

Generation belongs to publication. When a Trusted Snapshot successfully becomes
the canonical published snapshot, immutable Team State Share Artifacts are
generated for the league as the next step of the same lifecycle:

    publish_dashboard_snapshot()  (publication committed)
      -> run_post_publication_generation(snapshot)
      -> generate_team_state_artifacts_batch()   (SC-03B-01, unchanged)

This introduces no second generation pathway and no scheduler: it is invoked
only from the publication path, only after the publication has already committed.
It passes the authoritative publication context (the snapshot's id and product
date) straight into the existing batch service — it rediscovers nothing.

Failure semantics: publication is authoritative and already committed;
generation is strictly downstream. A generation failure therefore NEVER rolls
back or unpublishes the snapshot. This function fails closed and never raises —
an invalid/untrusted source or an unexpected error is logged and returned as
``None`` (each per-team attempt remains independently transactional exactly as
SC-03A guarantees, so no partial artifact is left behind). Reruns are idempotent
through the existing SC-01 deduplication.
"""

from __future__ import annotations

import logging
from typing import Optional

logger = logging.getLogger(__name__)


# Durable audit attribution for artifacts generated by the publication lifecycle.
POST_PUBLICATION_ACTOR = 'publication_hook'


def run_post_publication_generation(snapshot, *, generator=None):
    """Attempt league-wide Team State generation for a just-published snapshot.

    ``snapshot`` must be the snapshot that has already become the canonical
    published snapshot (``is_published`` True, publication committed). Returns the
    ``BatchGenerationResult`` on success, or ``None`` when generation could not be
    attempted or failed — never raising, so the authoritative publication is
    never affected.
    """
    if snapshot is None or not getattr(snapshot, 'is_published', False):
        # Defensive: only a published snapshot authorizes generation. A withheld
        # (pending/failed) snapshot must never trigger it.
        return None

    source_snapshot_id = getattr(snapshot, 'id', None)
    product_date = getattr(snapshot, 'data_through', None)
    if source_snapshot_id is None or product_date is None:
        logger.warning(
            'Post-publication generation skipped: snapshot_id=%s has no product date.',
            source_snapshot_id,
        )
        return None

    # Import lazily so importing this module (and the publication path) never
    # pulls the generation graph at load time.
    from services.share_artifact_batch_generation import (
        BatchSourceAuthorityError,
        BatchValidationError,
        generate_team_state_artifacts_batch,
    )

    try:
        result = generate_team_state_artifacts_batch(
            source_snapshot_id=source_snapshot_id,
            product_date=product_date,
            actor=POST_PUBLICATION_ACTOR,
            generator=generator,
        )
    except BatchSourceAuthorityError as exc:
        # The just-published snapshot is not (yet) a usable batch source. This is
        # a governed, non-fatal outcome: publication stands, no artifacts made.
        logger.warning(
            'Post-publication generation refused snapshot_id=%s: %s.',
            source_snapshot_id, exc.reason_code,
        )
        return None
    except BatchValidationError as exc:
        logger.error(
            'Post-publication generation input invalid snapshot_id=%s: %s.',
            source_snapshot_id, exc,
        )
        return None
    except Exception:
        # Downstream generation must never surface as a publication failure.
        logger.exception(
            'Post-publication generation failed non-fatally snapshot_id=%s.',
            source_snapshot_id,
        )
        return None

    logger.info(
        'Post-publication generation snapshot_id=%s product_date=%s: '
        'attempted=%s generated=%s reused=%s refused=%s failed=%s missing=%s.',
        source_snapshot_id, product_date, result.attempted_count,
        result.generated_count, result.reused_count, result.refused_count,
        result.failed_count, result.missing_count,
    )
    return result
