"""The exact set of generated `/team/{ABBR}` preview artifacts (DIST-003 / #594).

The change guards protect `frontend/` (and `frontend/public/` specifically) from
incidental edits. The routed team-preview pages live under that protection and
are regenerated by the daily export, so #594 has to name them.

Naming them is the point. This module exists so every guard allowlists the SAME
exact file list instead of reaching for a `frontend/public/**` directory
exemption: only these thirty-one paths are permitted, one per MLB club plus the
invalid-team fallback. A new file anywhere else under `frontend/public/` still
fails every guard, and adding a thirty-first club here is a visible, reviewable
edit rather than a silent widening.
"""

# The thirty MLB club abbreviations the export writes a preview page for, in the
# same alphabetical order the exporter emits them.
GENERATED_TEAM_PAGE_ABBREVIATIONS = (
    'ATH', 'ATL', 'AZ', 'BAL', 'BOS', 'CHC', 'CIN', 'CLE', 'COL', 'CWS',
    'DET', 'HOU', 'KC', 'LAA', 'LAD', 'MIA', 'MIL', 'MIN', 'NYM', 'NYY',
    'PHI', 'PIT', 'SD', 'SEA', 'SF', 'STL', 'TB', 'TEX', 'TOR', 'WSH',
)

# The invalid-team fallback. It makes no team claim and never has.
GENERATED_TEAM_FALLBACK_PAGE = 'frontend/public/team/index.html'

GENERATED_TEAM_PAGE_FILES = tuple(
    f'frontend/public/team/{abbreviation}/index.html'
    for abbreviation in GENERATED_TEAM_PAGE_ABBREVIATIONS
) + (GENERATED_TEAM_FALLBACK_PAGE,)
