"""add indexes and game_type

Revision ID: 018704c8d5fe
Revises: 3b06397ddc6b
Create Date: 2026-03-14 17:10:31.476303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018704c8d5fe'
down_revision = '3b06397ddc6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fatigue_scores', schema=None) as batch_op:
        batch_op.create_index('ix_fatigue_pitcher_calc', ['pitcher_id', 'calculated_at'], unique=False)

    with op.batch_alter_table('game_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_type', sa.String(length=2), nullable=True))
        batch_op.create_index('ix_game_log_game_pk', ['mlb_game_pk'], unique=False)
        batch_op.create_index('ix_game_log_game_type', ['game_type'], unique=False)
        batch_op.create_index('ix_game_log_pitcher_date', ['pitcher_id', 'game_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_game_log_pitcher_date')
        batch_op.drop_index('ix_game_log_game_type')
        batch_op.drop_index('ix_game_log_game_pk')
        batch_op.drop_column('game_type')

    with op.batch_alter_table('fatigue_scores', schema=None) as batch_op:
        batch_op.drop_index('ix_fatigue_pitcher_calc')

    # ### end Alembic commands ###
