"""create all tables

Revision ID: 3b06397ddc6b
Revises: 
Create Date: 2026-03-14 11:21:46.436009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b06397ddc6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mlb_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=True),
    sa.Column('team_abbreviation', sa.String(length=10), nullable=True),
    sa.Column('position', sa.String(length=10), nullable=True),
    sa.Column('throws', sa.String(length=1), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('jersey_number', sa.String(length=5), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mlb_id')
    )
    op.create_table('prospects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mlb_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('team_name', sa.String(length=100), nullable=True),
    sa.Column('team_abbreviation', sa.String(length=10), nullable=True),
    sa.Column('position', sa.String(length=10), nullable=True),
    sa.Column('bats', sa.String(length=1), nullable=True),
    sa.Column('throws', sa.String(length=1), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('current_level', sa.String(length=10), nullable=True),
    sa.Column('eta_year', sa.Integer(), nullable=True),
    sa.Column('hit_grade', sa.Integer(), nullable=True),
    sa.Column('power_grade', sa.Integer(), nullable=True),
    sa.Column('speed_grade', sa.Integer(), nullable=True),
    sa.Column('field_grade', sa.Integer(), nullable=True),
    sa.Column('arm_grade', sa.Integer(), nullable=True),
    sa.Column('overall_grade', sa.Integer(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('at_bats', sa.Integer(), nullable=True),
    sa.Column('batting_average', sa.Float(), nullable=True),
    sa.Column('on_base_pct', sa.Float(), nullable=True),
    sa.Column('slugging_pct', sa.Float(), nullable=True),
    sa.Column('ops', sa.Float(), nullable=True),
    sa.Column('home_runs', sa.Integer(), nullable=True),
    sa.Column('rbi', sa.Integer(), nullable=True),
    sa.Column('stolen_bases', sa.Integer(), nullable=True),
    sa.Column('strikeout_rate', sa.Float(), nullable=True),
    sa.Column('walk_rate', sa.Float(), nullable=True),
    sa.Column('era', sa.Float(), nullable=True),
    sa.Column('whip', sa.Float(), nullable=True),
    sa.Column('innings_pitched', sa.Float(), nullable=True),
    sa.Column('k_per_9', sa.Float(), nullable=True),
    sa.Column('bb_per_9', sa.Float(), nullable=True),
    sa.Column('fip', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mlb_id')
    )
    op.create_table('fatigue_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('pitch_count_score', sa.Float(), nullable=True),
    sa.Column('rest_days_score', sa.Float(), nullable=True),
    sa.Column('appearances_score', sa.Float(), nullable=True),
    sa.Column('leverage_score', sa.Float(), nullable=True),
    sa.Column('innings_score', sa.Float(), nullable=True),
    sa.Column('days_since_last_appearance', sa.Integer(), nullable=True),
    sa.Column('appearances_last_7', sa.Integer(), nullable=True),
    sa.Column('appearances_last_14', sa.Integer(), nullable=True),
    sa.Column('pitches_last_7_days', sa.Integer(), nullable=True),
    sa.Column('innings_last_7_days', sa.Float(), nullable=True),
    sa.Column('avg_leverage_last_7', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['pitcher_id'], ['pitchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('mlb_game_pk', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('opponent', sa.String(length=50), nullable=True),
    sa.Column('opponent_abbreviation', sa.String(length=10), nullable=True),
    sa.Column('innings_pitched', sa.Float(), nullable=True),
    sa.Column('pitches_thrown', sa.Integer(), nullable=True),
    sa.Column('strikes', sa.Integer(), nullable=True),
    sa.Column('hits_allowed', sa.Integer(), nullable=True),
    sa.Column('runs_allowed', sa.Integer(), nullable=True),
    sa.Column('earned_runs', sa.Integer(), nullable=True),
    sa.Column('walks', sa.Integer(), nullable=True),
    sa.Column('strikeouts', sa.Integer(), nullable=True),
    sa.Column('home_runs_allowed', sa.Integer(), nullable=True),
    sa.Column('leverage_index', sa.Float(), nullable=True),
    sa.Column('inherited_runners', sa.Integer(), nullable=True),
    sa.Column('inherited_runners_scored', sa.Integer(), nullable=True),
    sa.Column('save_situation', sa.Boolean(), nullable=True),
    sa.Column('hold', sa.Boolean(), nullable=True),
    sa.Column('blown_save', sa.Boolean(), nullable=True),
    sa.Column('win', sa.Boolean(), nullable=True),
    sa.Column('loss', sa.Boolean(), nullable=True),
    sa.Column('save', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pitcher_id'], ['pitchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_logs')
    op.drop_table('fatigue_scores')
    op.drop_table('prospects')
    op.drop_table('pitchers')
    # ### end Alembic commands ###
